{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "prometheus-smtp-exporter.fullname" . }}
  namespace: {{ template "prometheus-smtp-exporter.namespace" . }}
  labels:
    {{- include "prometheus-smtp-exporter.labels" . | nindent 4 }}  
spec:
  podSelector:
    matchLabels:
      {{- include "prometheus-smtp-exporter.selectorLabels" . | nindent 6 }}
  ingress:
{{- if .Values.networkPolicy.allowMonitoringNamespace }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
{{- else }}
  - {}
{{- end }}
  policyTypes:
  - Ingress
{{- end }}

