{{- if and .Values.pspEnabled (.Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy") }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  labels:
    {{- include "prometheus-smtp-exporter.labels" . | nindent 4 }}
  name: {{ template "prometheus-smtp-exporter.fullname" . }}
  namespace: {{ template "prometheus-smtp-exporter.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus-smtp-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus-smtp-exporter.serviceAccountName" . }}
{{- end -}}
